### ISSUE TITLE
solver panics when called twice

### ISSUE THREAD

**Issue by mmaroti** [c-cube/batsat#7]
Using this test program

```rust
extern crate batsat;
use batsat::callbacks::Basic;
use batsat::clause::{lbool, Lit, Var};
use batsat::core::Solver;
use batsat::SolverInterface;

pub fn main() {
    let mut solver: Solver<Basic> = Solver::new(Default::default(), Default::default());

    let a = Lit::new(solver.new_var_default(), false);
    let b = Lit::new(solver.new_var_default(), false);
    assert!(solver.add_clause_reuse(&mut vec![a, b]));
    assert_eq!(solver.solve_limited(&[!b]), lbool::TRUE);
    assert!(solver.add_clause_reuse(&mut vec![!a, b]));
    assert!(solver.add_clause_reuse(&mut vec![!a, !b]));
    solver.solve_limited(&[]);
}
```
I am seeing a panic in the last line with the error `thread 'main' panicked at 'attempt to subtract with overflow'`. I think this should not happen as you can add clauses between calling the solver in the original minisat and in all other sat solvers that I have tried (varisat, cryptominisat, minisat crate).

**Comment by c-cube** [comment]
Can you retry using master, actually? I can reproduce that on 3.1 but not on master.

**Comment by mmaroti** [comment]
I have used 3.1, sorry for not testing the master branch. I will do a test now.

**Comment by c-cube** [comment]
No worries! :slightly_smiling_face:

**Comment by mmaroti** [comment]
The same code panics for me on the master branch! I have used the debug build.

**Comment by c-cube** [comment]
yep, same for me, I was testing in release. CI catches it now at least. Thanks for trying!

**Comment by mmaroti** [comment]
Downloaded your latest master branch in a pristine directory and run `cargo test` and it fails within the new `interface::test::test_reg7`.

**Comment by mmaroti** [comment]
Excellent, at least you can reproduce it. Thanks for looking into this.

**Comment by mmaroti** [comment]
Thanks for the fix, it works for my real problems as well, and it is fast!

**Comment by c-cube** [comment]
glad to hear that! What are you using the solver for? :slightly_smiling_face:

**Comment by mmaroti** [comment]
Universal algebraic (pure math) research, porting an old code base from java to rust: https://github.com/mmaroti/uasat-rs

**Comment by c-cube** [comment]
0.4 was just released btw, you may want to update your cargo file :)

**Comment by mmaroti** [comment]
Excellent, thanks, I will do that. Miklos
